In [2]:
!pip install numpy
import numpy as np

rand_num = np.random.default_rng()

1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
a = np.zeros((3,3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
a = rand_num.integers(1, 10, size=(5,5))
print(a)

[[4 8 7 8 9]
 [1 1 9 1 5]
 [3 7 6 7 5]
 [6 2 8 7 1]
 [8 9 7 9 4]]


4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
a = rand_num.random((4,4))
print(a)

[[0.30386323 0.86044125 0.21827543 0.08348773]
 [0.45949921 0.39594185 0.16069986 0.81198755]
 [0.02711024 0.105323   0.34641721 0.24584108]
 [0.62953423 0.81130836 0.28343728 0.72762579]]


5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
a = rand_num.integers(1,10, size=(5,))
b = rand_num.integers(1,10, size=(5,))
add_ =a + b
sub_ = a - b
multiply_ = a * b
print(f'Add: {add_}')
print(f'Sub: {sub_}')
print(f'Multiply: {multiply_}')

Add: [14  7 13  9 17]
Sub: [ 0 -5 -1 -1 -1]
Multiply: [49  6 42 20 72]


6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
a = np.arange(1,14,2)
b = np.arange(0,7)
print(f'Scalar of {a} and {b}: {np.dot(a, b)}')


Scalar of [ 1  3  5  7  9 11 13] and [0 1 2 3 4 5 6]: 203


7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
a = rand_num.integers(1,10, (2,2))
b = rand_num.integers(1,10, (2,3))
print(a@b)

[[60 48 28]
 [30 22 32]]


8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
a = rand_num.integers(1,10, (3,3))
a_inv = np.linalg.inv(a)
print(f'Inverse Matrix of\n {a}\n is\n {a_inv.round(4)}')

Inverse Matrix of
 [[6 2 8]
 [5 7 2]
 [5 7 8]]
 is
 [[ 0.2188  0.2083 -0.2708]
 [-0.1562  0.0417  0.1458]
 [ 0.     -0.1667  0.1667]]


9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
a = rand_num.random(size=(4,4))
print(a.round(4))

[[0.6664 0.7035 0.5992 0.4843]
 [0.0987 0.2759 0.8095 0.5126]
 [0.9981 0.5467 0.7572 0.1528]
 [0.7535 0.4556 0.7895 0.0169]]


10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
a = rand_num.integers(1,10, size=(3,4))
b = np.random.randint(1,10, size=(4,))
print(a@b)

[ 65  79 109]


11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
a = rand_num.random((2,3))
b = rand_num.random((3,))
print(np.dot(a, b).round(4))

[0.7415 1.2547]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
a = rand_num.integers(1,10, size=(2,2))
b = rand_num.integers(1,10, size=(2,2))
print(a, b, a * b, sep='\n\n')


[[6 4]
 [5 9]]

[[8 8]
 [7 3]]

[[48 32]
 [35 27]]


13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
a = rand_num.integers(1,10, (2,2))
b = rand_num.integers(1,10, (2,2))
print(a, b, np.dot(a, b), sep='\n\n')

[[7 8]
 [5 3]]

[[4 7]
 [5 6]]

[[68 97]
 [35 53]]


14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
a = rand_num.integers(1,100, (5,5))
b = np.sum(a)
print(f'Sum of array:\n {a}\n= {b}')

Sum of array:
 [[13 57 43 95 77]
 [68 19 30 50 65]
 [ 7 86 20 49 21]
 [21 54 59 59 41]
 [78 51  8 92 54]]
= 1217


15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
a = rand_num.integers(1,10, (4,4))
b = rand_num.integers(1,10, (4,4))
#print(np.subtract(a,b))
print(a-b)

[[ 5  2  1 -2]
 [ 7  0  1  1]
 [ 1  1  6 -5]
 [-5  5  4  5]]
[[ 5  2  1 -2]
 [ 7  0  1  1]
 [ 1  1  6 -5]
 [-5  5  4  5]]


16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [19]:
a = rand_num.random(size=(3,3))
print(a.round(4), np.sum(a, axis=1).round(4), sep='\n\n')

[[0.047  0.1674 0.5469]
 [0.9431 0.8905 0.1415]
 [0.9768 0.9099 0.1339]]

[0.7613 1.9751 2.0206]


17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [36]:
a = np.arange(1,13)
b = a.reshape(3,4)
print(np.square(b))

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [43]:
a = rand_num.integers(1,50,4)
print(a, np.sqrt(a).round(4), sep='\n')

[47 37 28 34]
[6.8557 6.0828 5.2915 5.831 ]
